Http request
dobisel/httpload pull request #40
Opened 2021-04-15 10:21 UTC by NothingRealm

This is a simple implemention for creating HTTP packets and writing them directly to a file descriptor.

2021-04-15 13:23 UTC, pylover requested changes
First, thanks a lot for this PR.

Please pass tests before sending any PR.

2021-04-15 13:23 UTC, pylover commented on http_request.c
> +int write_verb_path(const int fd, const char* verb, const char* path) {
`const int fd` Nice idea. :+1:

2021-04-15 13:23 UTC, pylover commented on http_request.c
> +    int i, err, sum = 0;
Please define at most one variable per line.

```C
int foo;
int bar;
int baz;
```

2021-04-15 13:23 UTC, pylover commented on http_request.c
> +    return dprintf(fd, "HOST: %s\r\n", host);
```C
return dprintf(fd, "HOST: %s" RN, host);
```

2021-04-15 13:23 UTC, pylover commented on http_request.c
> +        if (err < 0)
Please always use `{}` for if blocks.

```C
if (err) {
    // handle err
}
```

2021-04-15 13:23 UTC, pylover commented on http_request.c
> +            return -1;
```C
#include <common.h>
.....
return ERR;
```

2021-04-15 13:23 UTC, pylover commented on http_request.c
> +    err = write(fd, body, strlen(body));
Do not use `strlen()` here to get rid of possible null characters inside body. 

And please pass the length of `body` from the caller.

2021-04-15 13:23 UTC, pylover commented on http_request.c
> +int send_request(
Please do not folow the rule: `one-item-per-line` jsut for the function definitions.

an example of function definition:

```C
int rb_dryread_until(struct ringbuffer *b, char *data, size_t len,
                     char *delimiter, size_t dlen, size_t *readlen);
```

2021-04-15 13:23 UTC, pylover commented on http_request.h
> +#define CR "\r\n"
The `NR` macro is already defined inside `common.h`

2021-04-15 13:23 UTC, pylover commented on http_request.h
> +#define HTTP_VERSION "HTTP/1.0"
We need both `1.0` and `1.1` HTTP versions.

2021-04-15 13:23 UTC, pylover commented on tests/test_http_request.c
> +#define PATH "/tmp/http_request.txt"
Use `tempnam(3)` instead of the static temporary file name.

2021-04-15 13:23 UTC, pylover commented on tests/test_http_request.c
> +int
Use macro instead of function.

2021-04-15 13:23 UTC, pylover commented on tests/test_http_request.c
> +    char* host = "google.com";
Bad idea:

```C
char* c;
char * c;
```

Good idea:

```C
char *c;
```

2021-04-15 13:23 UTC, pylover commented on tests/test_http_request.c
> +    expected = (char*) malloc(len * sizeof(char));
Do not allocate here.

Simply use: 

```C
eqstr(" ....", ...)
```

With static host argument.

2021-04-15 13:23 UTC, pylover commented on tests/test_http_request.c
> +    response = (char*) malloc(len * sizeof(char));
And always free what you allocated.

2021-04-15 13:23 UTC, pylover commented on tests/test_http_request.c
> +    char* body = "{\"name\": \"Dennis\", \"lastname\": \"Ritchie\"}";
Simply use `foo bar baz` instead of ugly json `{}` and unwanted quotes: `"`.

2021-04-15 13:23 UTC, pylover commented on tests/test_http_request.c
> +    notequalint(-1, len);
```C
notequalint(ERR, len)
```

2021-04-15 13:23 UTC, pylover commented on tests/test_http_request.c
> +    test_write_verb_path();
Please insert:

```C
log_setlevel(LL_DEBUG)
```

At the first line of the test `main()`  functions.

2021-04-15 20:35 UTC, NothingRealm commented
As I noticed from action logs I think the reason pipeline fails is because of coveralls token. And there is a test for test_server_cli which fails and I noticed that one failed on master branch pipline too but the check is given to the branch.

2021-04-16 12:13 UTC, pylover commented
Let I check it, coveralls token is already available in repo secrets.

And if any test is failing in your machine, please submit an issue and provide appropriate information to investigate and fix it.

2021-04-16 15:27 UTC, NothingRealm commented
I added a condition to pipeline so coveralls would be skipped on PRs

2021-04-18 08:10 UTC, pylover commented
I'll merge it asap.

2021-04-27 07:06 UTC, merged